### ISSUE TITLE
bug: self-hosted resend email integration not working

### ISSUE THREAD

**Issue by sallespro** [triggerdotdev/trigger.dev#1592]
### Provide environment information

i installed the current coolify service edition of trigger.dev

### Describe the bug

Out of the box, it acts as if e-mail is sent, but is is not.  Looking closer, i noticed a missing env Variable, when `EMAIL_TRANSPORT` is included, it fails with `API Key invalid`

### Reproduction repo

https://trigger.dev/docs/open-source-self-hosting

### To reproduce

install trigger.dev using coolify and try to login.

**Comment by matt-aitken** [comment]
@sallespro do you have a valid Resend API key set? We use Resend on our cloud product and so I can confirm that this does work.

**Comment by sallespro** [comment]
hi, i do have and can confirm it works as well. 
Another anomaly is regarding redis in trigger container logs .

```2025-01-09T15:03:38.280584275Z [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
2025-01-09T15:03:38.280645429Z     at parseError (/triggerdotdev/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
2025-01-09T15:03:38.280652643Z     at parseType (/triggerdotdev/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
2025-01-09T15:03:38.281882890Z [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required. ```

**Comment by sallespro** [comment]
i did a fresh install and despite setting the RESEND_API_KEY, the email is not sent. This means looking at logs to get the magic link...this means a major problem just to onboard trigger...

Another thing is some account data that is kept locally when `npx trigger.dev@latest init -p...` is run. i am using a different account name ant i can't get rid of this hidden cache... so i can not create a project because there's some missmatch .

```% npx trigger.dev@latest init -p proj_etc -a https://domain.com

Trigger.dev (3.3.9)
------------------------------------------------------
┌  Initializing project
│
◇  Retrieved your account details for sallespro@gmail.com
│
■  --project-ref proj_etc is not a valid project ref. Request to fetch data resulted in: 404 "Project not found"
```
I wish i could help to debug, but now it is not possible. So i hope this shows how difficult it is to take the self host way.

**Comment by matt-aitken** [comment]
Can you explain a bit more about what guide you followed?

The Coolify template isn't official and I know it has some issues – there's an open Pull Request on Coolify here: https://github.com/coollabsio/coolify/pull/4724

We have a self-hosting community who might also be helpful using Coolify with Trigger.dev here: https://trigger.dev/discord

**Comment by sallespro** [comment]
Oh, i see. in this case i'll use the cloud version and hope this is fixed in the future. thank you

**Comment by abudioutbond** [comment]
You can fix Auth emails by adding this line to all environments sections in the docker compose file `EMAIL_TRANSPORT: 'resend'`
However, I still can't enable the email alerts for some reason, although the email invitations and magic links work fine

**Comment by abudioutbond** [comment]
I also could fix the Alerts issue by adding those 4 lines to the docker compose file too:
`      ALERT_EMAIL_TRANSPORT: '${ALERT_EMAIL_TRANSPORT}'
      ALERT_FROM_EMAIL: '${ALERT_FROM_EMAIL}'
      ALERT_REPLY_TO_EMAIL: '${ALERT_REPLY_TO_EMAIL}'
      ALERT_RESEND_API_KEY: '${ALERT_REPLY_TO_EMAIL}'`
